package com.am.entities;
// Generated Nov 7, 2017 10:45:06 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jobsheet generated by hbm2java
 */
public class Jobsheet implements java.io.Serializable {

	private int jobsheetNo;
	private Advisor advisor;
	private Customer customer;
	private ServiceCenter serviceCenter;
	private Vehicle vehicle;
	private Date openedDt;
	private int kilometers;
	private String petrolLevel;
	private String jobSheetType;
	private int estimatedAmount;
	private String deliveryEta;
	private String status;
	private Set<JobsheetRepairs> jobsheetRepairses = new HashSet<JobsheetRepairs>(0);
	private Set<JobsheetSparepart> jobsheetSpareparts = new HashSet<JobsheetSparepart>(0);
	private Set<JobsheetMechanic> jobsheetMechanics = new HashSet<JobsheetMechanic>(0);
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public Jobsheet() {
	}

	public Jobsheet(int jobsheetNo, Advisor advisor, Customer customer, ServiceCenter serviceCenter, Vehicle vehicle,
			Date openedDt, int kilometers, String petrolLevel, String jobSheetType, int estimatedAmount,
			String deliveryEta, String status) {
		this.jobsheetNo = jobsheetNo;
		this.advisor = advisor;
		this.customer = customer;
		this.serviceCenter = serviceCenter;
		this.vehicle = vehicle;
		this.openedDt = openedDt;
		this.kilometers = kilometers;
		this.petrolLevel = petrolLevel;
		this.jobSheetType = jobSheetType;
		this.estimatedAmount = estimatedAmount;
		this.deliveryEta = deliveryEta;
		this.status = status;
	}

	public Jobsheet(int jobsheetNo, Advisor advisor, Customer customer, ServiceCenter serviceCenter, Vehicle vehicle,
			Date openedDt, int kilometers, String petrolLevel, String jobSheetType, int estimatedAmount,
			String deliveryEta, String status, Set<JobsheetRepairs> jobsheetRepairses,
			Set<JobsheetSparepart> jobsheetSpareparts, Set<JobsheetMechanic> jobsheetMechanics, Set<Invoice> invoices) {
		this.jobsheetNo = jobsheetNo;
		this.advisor = advisor;
		this.customer = customer;
		this.serviceCenter = serviceCenter;
		this.vehicle = vehicle;
		this.openedDt = openedDt;
		this.kilometers = kilometers;
		this.petrolLevel = petrolLevel;
		this.jobSheetType = jobSheetType;
		this.estimatedAmount = estimatedAmount;
		this.deliveryEta = deliveryEta;
		this.status = status;
		this.jobsheetRepairses = jobsheetRepairses;
		this.jobsheetSpareparts = jobsheetSpareparts;
		this.jobsheetMechanics = jobsheetMechanics;
		this.invoices = invoices;
	}

	public int getJobsheetNo() {
		return this.jobsheetNo;
	}

	public void setJobsheetNo(int jobsheetNo) {
		this.jobsheetNo = jobsheetNo;
	}

	public Advisor getAdvisor() {
		return this.advisor;
	}

	public void setAdvisor(Advisor advisor) {
		this.advisor = advisor;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public ServiceCenter getServiceCenter() {
		return this.serviceCenter;
	}

	public void setServiceCenter(ServiceCenter serviceCenter) {
		this.serviceCenter = serviceCenter;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Date getOpenedDt() {
		return this.openedDt;
	}

	public void setOpenedDt(Date openedDt) {
		this.openedDt = openedDt;
	}

	public int getKilometers() {
		return this.kilometers;
	}

	public void setKilometers(int kilometers) {
		this.kilometers = kilometers;
	}

	public String getPetrolLevel() {
		return this.petrolLevel;
	}

	public void setPetrolLevel(String petrolLevel) {
		this.petrolLevel = petrolLevel;
	}

	public String getJobSheetType() {
		return this.jobSheetType;
	}

	public void setJobSheetType(String jobSheetType) {
		this.jobSheetType = jobSheetType;
	}

	public int getEstimatedAmount() {
		return this.estimatedAmount;
	}

	public void setEstimatedAmount(int estimatedAmount) {
		this.estimatedAmount = estimatedAmount;
	}

	public String getDeliveryEta() {
		return this.deliveryEta;
	}

	public void setDeliveryEta(String deliveryEta) {
		this.deliveryEta = deliveryEta;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<JobsheetRepairs> getJobsheetRepairses() {
		return this.jobsheetRepairses;
	}

	public void setJobsheetRepairses(Set<JobsheetRepairs> jobsheetRepairses) {
		this.jobsheetRepairses = jobsheetRepairses;
	}

	public Set<JobsheetSparepart> getJobsheetSpareparts() {
		return this.jobsheetSpareparts;
	}

	public void setJobsheetSpareparts(Set<JobsheetSparepart> jobsheetSpareparts) {
		this.jobsheetSpareparts = jobsheetSpareparts;
	}

	public Set<JobsheetMechanic> getJobsheetMechanics() {
		return this.jobsheetMechanics;
	}

	public void setJobsheetMechanics(Set<JobsheetMechanic> jobsheetMechanics) {
		this.jobsheetMechanics = jobsheetMechanics;
	}

	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
