package com.am.entities;
// Generated Nov 7, 2017 10:45:06 AM by Hibernate Tools 4.3.5.Final

/**
 * JobsheetRepairs generated by hbm2java
 */
public class JobsheetRepairs implements java.io.Serializable {

	private int repairId;
	private String repair;
	private Jobsheet jobsheet;
	public int getRepairId() {
		return repairId;
	}
	public void setRepairId(int repairId) {
		this.repairId = repairId;
	}
	public String getRepair() {
		return repair;
	}
	public void setRepair(String repair) {
		this.repair = repair;
	}
	public Jobsheet getJobsheet() {
		return jobsheet;
	}
	public void setJobsheet(Jobsheet jobsheet) {
		this.jobsheet = jobsheet;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((jobsheet == null) ? 0 : jobsheet.hashCode());
		result = prime * result + ((repair == null) ? 0 : repair.hashCode());
		result = prime * result + repairId;
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		JobsheetRepairs other = (JobsheetRepairs) obj;
		if (jobsheet == null) {
			if (other.jobsheet != null)
				return false;
		} else if (!jobsheet.equals(other.jobsheet))
			return false;
		if (repair == null) {
			if (other.repair != null)
				return false;
		} else if (!repair.equals(other.repair))
			return false;
		if (repairId != other.repairId)
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "JobsheetRepairs [repairId=" + repairId + ", repair=" + repair
				+ ", jobsheet=" + jobsheet + "]";
	}

	

}
